# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181205_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='qualification',
            field=models.CharField(max_length=40),
        ),
    ]
